version: '3.7'

services:
  nginx:
    build: .
    container_name: nginx1
    volumes:
      - nimdi_media:/vol/media
      - static_data:/vol/static
      - .:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - nimdi_app
    networks:
      - mynet

volumes:
   postgres_data:
   nimdi_media:
   static_data:

networks:
   mynet: